### ISSUE TITLE
This is becoming tiring

### ISSUE THREAD

**Issue by Czaste** [bobstrickland03/Angular2-RESTfulService#1]
This is now the 3rd 'Learning Angular 2' site I've cloned and worked with, and at this point I have had it.

Although 'installation' instructions are followed to the letter, the site will not start (js server), and nothing can be done with any of the code nor the pluralsight course.

If you are going to publish a course (especially one that costs money), it would be a wise business practice to follow through and **MAKE SURE** that your **INSTALLATION INSTRUCTIONS** work as promised. I've combed through the js code and cannot find any obvious answer to this problem.

Please fix this, or take it off of GitHub. 

Thank you.

**Comment by bobstrickland03** [comment]
I am sorry for the inconvenience to you.  I pulled this repo from  someone else and it was me playing around with code.  I recommend you go to https://github.com/angular/quickstart for a good starting point of Angular.  I will fix this or take it off of GitHub within a week.

**Comment by Czaste** [comment]
Thank you.
